### ISSUE TITLE
能添加 类似 iConsole 那样的功能吗？

### ISSUE THREAD

**Issue by yushuyi** [DotzuX/DotzuX#10]
输入自定义 的 命令  执行自定义的代码
https://github.com/nicklockwood/iConsole

**Comment by DotzuX** [comment]
[TinyConsole](https://github.com/Cosmo/TinyConsole) 不能替代 [iConsole](https://github.com/nicklockwood/iConsole) 吗？

**Comment by yushuyi** [comment]
可以呢，谢谢
