### ISSUE TITLE
使用过程中 遇到两个Bug

### ISSUE THREAD

**Issue by yushuyi** [DotzuX/DotzuX#11]
引入 DotzuX 以后 
1：项目禁止了横屏， 但是横竖屏的时候， 界面跳动了一下， 随便还是竖屏的，但是这感觉很奇怪
2：顶部状态栏 黑色 白色 的切换 也因为 启动了DotzuX ， 重写系统方法 变得无效。

**Comment by DotzuX** [comment]
请问你用的cocoapods还是carthage导入的？
导入的DotzuX版本号是？

**Comment by yushuyi** [comment]
@DotzuX  Pod 引入， 版本是 (0.1.0)

**Comment by DotzuX** [comment]
试一下 `pod update DotzuX ` 
pod有更新

**Comment by DotzuX** [comment]
升级到新本版后，问题解决了吗？ 
@yushuyi

**Comment by yushuyi** [comment]
@DotzuX 谢谢，我晚些尝试下

**Comment by yushuyi** [comment]
@DotzuX 我更新了最新的， 上面两个问题 还存在

**Comment by DotzuX** [comment]
- 第一个bug，你是自己的项目禁用了横屏，然后把手机横着放是吗？`界面跳动了一下`是指进入DotzuX调试界面之后还是之前？还是退出了DotzuX调试界面之后呢？`随便还是竖屏`是指？
- 第二个bug，`顶部状态栏 黑色 白色 的切换`是指切换背景色还是字体颜色？

两个bug确定是导入DotzuX引起的吗？能提供视频或者截图更好。
当然，[pull requests](https://github.com/DotzuX/DotzuX/pulls)你的bugfix代码，一起来改进DotzuX就更好了。
谢谢~
