### ISSUE TITLE
Wrong color for http code over 201

### ISSUE THREAD

**Issue by YannickSteph** [DotzuX/DotzuX#13]
<img width="115" alt="capture d ecran 2018-04-17 a 22 22 06" src="https://user-images.githubusercontent.com/6950194/38908379-e68efd46-428d-11e8-9b51-8fd78575446d.png">

Color for http code over 201 are red in log for the request.

DotzuX (0.1.5)

**Comment by DotzuX** [comment]
Sorry. I will fix it soon. Now only 200 is green.

**Comment by DotzuX** [comment]
I reference from here https://httpstatuses.com/
