### ISSUE TITLE
No report of message

### ISSUE THREAD

**Issue by YannickSteph** [DotzuX/DotzuX#14]
<img width="343" alt="capture d ecran 2018-04-17 a 22 02 03" src="https://user-images.githubusercontent.com/6950194/38907708-0f3c6b6e-428b-11e8-86cc-9f179144a6b7.png">
<img width="334" alt="capture d ecran 2018-04-17 a 22 02 19" src="https://user-images.githubusercontent.com/6950194/38907709-0f4fd032-428b-11e8-9a21-648c4d409001.png">

I don't have my report of my error.

This is my code

```
        #if DEBUG
            let description = "\n[\(reportType.logo())]\n👉\(error)\n👈"
            let color: UIColor
            switch reportType {
            case .error:    color = UIColor.red
            case .warning:  color = UIColor.orange
            case .info:     color = UIColor.yellow
            }
            swiftLog(file, function, inLine, description, color)
        #endif
```

DotzuX (0.1.5)

do you need some more information ?

**Comment by DotzuX** [comment]
That is strange. My example project just works fine. This bug just appear in 0.1.5 ？

**Comment by DotzuX** [comment]
I will try your code in my demo later.

**Comment by DotzuX** [comment]
I know why now, I will fix it soon~ (see here)

![example](https://raw.githubusercontent.com/DotzuX/DotzuX/master/pic/issue-14.gif)

**Comment by lailavinson** [comment]
I have this same problem on iOS 10.3.3, using iPhone 5. The same code works in iOS 11.3, using iPhone 7. This issue happens regardless of how I set the UIColor (or if I omit the color argument).

The dates are showing up correctly in realtime, but there is no other information.

**Comment by lailavinson** [comment]
@DotzuX  It works! Thanks for the quick fix :)
