### ISSUE TITLE
给demo 里面 的 NSLog换了个 名字 然后 使用NSLog 出现 警告

### ISSUE THREAD

**Issue by sos1a2a3a** [DotzuX/DotzuX#15]
警告：Expression result unused

方法 objcLog 也没有 返回值啊 

求解 

谢谢

具体的 是这样 ：

想打印 一个 int 或者 float 或者  NSInteger 数值

NSLog(@"num:%ld",index);
报错：Implicit conversion of 'int' to 'id _Nonnull' is disallowed with ARC

然后我转成 NSNumber

NSLog(@"num:%@",[NSNumber numberWithInt:index]);

就出现 警告：Expression result unused

**Comment by sos1a2a3a** [comment]
object-c 项目

**Comment by DotzuX** [comment]
没太明白你的意思，你用`cocoapods`还是`carthage`导入的？有完整代码或截图吗？谢谢!

**Comment by sos1a2a3a** [comment]
解决了  少写一句话 
#pragma clang diagnostic ignored "-Wunused-value"
