### ISSUE TITLE
PR #12 bug fix

### ISSUE THREAD

**Issue by Kofktu** [DotzuX/DotzuX#16]
HI,
I did a PR a few days ago and a bug has been found in iOS 10 and below.

And I want to actually use Swift.print or NSLog in the app in the log section, 
and use the part of DotzuX that is shown in LogViewController separately.

**Comment by DotzuX** [comment]
cocoapods 0.1.6 is published.

**Comment by DotzuX** [comment]
Fixed [Issues-14](https://github.com/DotzuX/DotzuX/issues/14), and [Readme](https://github.com/DotzuX/DotzuX#usage) changed a little. Just see here: 

thanks for help @Kofktu 

![pic](https://raw.githubusercontent.com/DotzuX/DotzuX/master/pic/issue-14.png)
