### ISSUE TITLE
Can you optimize your UI

### ISSUE THREAD

**Issue by Album1993** [DotzuX/DotzuX#18]
the icons and the black theme is not suitable for all application , can you provide some custom options for the interface

**Comment by DotzuX** [comment]
What do you mean `the icons and the black theme is not suitable for all application`?

Can you provide some screenshots. This would be gread help for me to understand your words.

You can pull your own codes (PR) to `provide some custom options for the interface`. This would save both your and my time. 

thanks @Album1993

**Comment by Album1993** [comment]
我的意思是你的UI不是很让所有人满意。其实你可以给一些可配置的选项，将所有的图标还有字体都由那个configration来统一管理，平时我们可以自定义颜色，自定义按钮的图片，这样的话可能更好

**Comment by CocoaDebug** [comment]
新版本已经支持自定义颜色，请及时更新，谢谢
