### ISSUE TITLE
Disable method

### ISSUE THREAD

**Issue by MarcoAlessandroRiggio** [DotzuX/DotzuX#19]
Permits to disable DotzuX at runTime.

**Comment by pippolino** [comment]
Hi,

It would be great to be able to enable and disable it, as [Dotzu](https://github.com/remirobert/Dotzu) does.

Thanks so much @DotzuX !!!

**Comment by DotzuX** [comment]
Nice idea, I will release new version as soon as possible.

**Comment by DotzuX** [comment]
🚀  DotzuX (0.2.1) successfully published.
Please have a try. @MarcoAlessandroRiggio @pippolino

**Comment by pippolino** [comment]
Amazing! super fast, thank you very much @DotzuX . It works very well!
