### ISSUE TITLE
Log Ephemeral session

### ISSUE THREAD

**Issue by MarcoAlessandroRiggio** [DotzuX/DotzuX#20]
Actually, ephemeral session aren't logged in network log.
Is correct or we wrong something?
We need to log also this type of session, it can be possible?

Thanks

**Comment by DotzuX** [comment]
`ephemeral session` , you mean this?

[ephemeral](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1410529-ephemeral)

**Comment by DotzuX** [comment]
🚀  DotzuX (0.2.3) successfully published @MarcoAlessandroRiggio 

- support [defaultSessionConfiguration](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411560-defaultsessionconfiguration?language=objc)
- support [ephemeralSessionConfiguration](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1410529-ephemeralsessionconfiguration?language=objc)
- support [backgroundSessionConfiguration:](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1411521-backgroundsessionconfiguration) `Deprecated `
- support [backgroundSessionConfigurationWithIdentifier:](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1407496-backgroundsessionconfigurationwi?language=objc)

**Comment by MarcoAlessandroRiggio** [comment]
We have open the issue #21 because can't verify the resolution of this issue.

Thanks 
Marco

**Comment by DotzuX** [comment]
🚀  DotzuX (0.2.4) published.
Sorry for coming late~

**Comment by MarcoAlessandroRiggio** [comment]
@DotzuX Everything work correctly.
Thanks a lot for your celerity.
Great Job.
