### ISSUE TITLE
UrlSession willPerformHTTPRedirection failed when import module

### ISSUE THREAD

**Issue by MarcoAlessandroRiggio** [DotzuX/DotzuX#21]
Hi,

when import the module DotzuX in the project, the delegate method [willPerformHTTPRedirection](https://developer.apple.com/documentation/foundation/nsurlsessiontaskdelegate/1411626-urlsession) of URLSessionTaskDelegate never called, but if we remove the module (remove completely from the project not only remove import) the method was called correctly.

This behavior only manifested using [URLSessionConfiguration.default](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411560-default), but from version 0.2.3 also with [URLSessionConfiguration.ephemeral](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1410529-ephemeral)

In attached, a sample project that reproduces the problem.
[DemoRedirect.zip](https://github.com/DotzuX/DotzuX/files/2004047/DemoRedirect.zip)

Thanks
Marco

**Comment by DotzuX** [comment]
OK, I will fix it tomorrow~  Thanks for waiting....

**Comment by DotzuX** [comment]
🚀  DotzuX (0.2.4) published.
Sorry for coming late~

**Comment by MarcoAlessandroRiggio** [comment]
@DotzuX Everything work corectly.
Thanks a lot for your celerity.
Great Job.
