### ISSUE TITLE
Share Log

### ISSUE THREAD

**Issue by MarcoAlessandroRiggio** [DotzuX/DotzuX#23]
Hi,
Is possible have a new feature to share log via email?

Thanks
Best Regards

**Comment by DotzuX** [comment]
Which log you want to share? Network-Log or Print()-Log ?

**Comment by DotzuX** [comment]
This week (Friday)，I will fix this. Thanks！

**Comment by DotzuX** [comment]
version (0.3.8) released. 
See [README](https://github.com/DotzuX/DotzuX#new-feature-038)
