### ISSUE TITLE
Carthage support (question)

### ISSUE THREAD

**Issue by romanfurman6** [DotzuX/DotzuX#8]
Hey, it possible to add Carthage support?

**Comment by liman123** [comment]
Sorry, DebugMan does not support Carthage now.
I will try my best to release new version for supporting Carthage this weekend~

**Comment by romanfurman6** [comment]
@liman123 thanks <3

**Comment by DotzuX** [comment]
Thanks for waiting, sorry for coming late~  Now support Carthage.
 I just renamed as `DotzuX` for respecting to [Dotzu](https://github.com/remirobert/Dotzu)

`github "DotzuX/DotzuX"`

**Comment by DotzuX** [comment]
There are more features in [DotzuX](https://github.com/DotzuX/DotzuX), just see README.

**Comment by romanfurman6** [comment]
@DotzuX it’s great, thanks 👏🏻
