### ISSUE TITLE
StatusBarColor Changed by DotzuX

### ISSUE THREAD

**Issue by jihongboo** [DotzuX/DotzuX#9]
In our project, the StatusBarColor was light. But when we import DotzuX to our project, the StatusBarColor became black.

**Comment by DotzuX** [comment]
In which way you import `DotzuX`? `cocoapods` or `carthage`?

**Comment by jihongboo** [comment]
cocoapods

**Comment by DotzuX** [comment]
what's your iOS version?

**Comment by DotzuX** [comment]
can you upload your screenshoot before and after import `DoztuX`? thanks

**Comment by DotzuX** [comment]
Fixed, please run `pod update DotzuX`
